#!/bin/bash

source build/deploy/color

# This installs all the correct endpoints
# for all the tailwind servers
# It will also remove anything other than the origin
# So if you have other endpoints you should probably save them
# or just not run this script

if [ $1 ]

then

cat >build/deploy/config <<EOL
SSH_USER=$1
HIPCHAT_USER="\$SSH_USER-bot"
EOL


if [ -f build/deploy/config ]
then
    printf "%b\n" "$GREEN Added config file to buid/deploy/config. $WHITE"
else
    printf "%b\n" "$RED I wasn't able to build the config file. Are you sure you have write permissions in the build dir? Try as sudo$WHITE"

fi

else

printf "%b" "$RED"
echo 'Hmm, I need your name for accessing the servers via ssh.'
printf "%b" "$WHITE"
echo 'So if you ssh like this: ssh bob@servername you would use'
echo ''
echo './install.sh bob'
echo ''

fi