<?php

/**
 * Class FeaturesSeeder
 * Creates the defaults for features table
 */
class FeaturesSeeder extends Seeder
{

    /**
     * Seeds the features table with defaults
     */
    public function run()
    {

        $defaults = array(
            ['pin_scheduling_enabled', 0],
            ['listening_enabled', 0],
            ['content_enabled', 0],
            ['nav_profile', 1],
            ['nav_boards', 1],
            ['nav_website', 0],
            ['nav_pins', 0],
            ['nav_category', 1],
            ['nav_day_time', 0],
            ['nav_trending_pins', 1],
            ['nav_fans', 0],
            ['nav_traffic', 1],
            ['nav_roi_pins', 0],
            ['nav_roi_pinners', 0],
            ['nav_comp_bench', 0],
            ['nav_listen', 0],
            ['nav_add_account', 0],
            ['nav_add_user', 0],
            ['profile_date_7_days', 0],
            ['profile_date_14_days', 0],
            ['profile_date_30_days', 0],
            ['profile_date_custom', 0],
            ['profile_history_90', 0],
            ['profile_history_180', 0],
            ['profile_history_all', 0],
            ['profile_chart_repins', 0],
            ['profile_chart_likes', 0],
            ['profile_gauges', 0],
            ['profile_export', 0],
            ['boards_date_7_days', 0],
            ['boards_date_14_days', 0],
            ['boards_date_30_days', 0],
            ['boards_date_custom', 0],
            ['boards_history_90', 0],
            ['boards_history_180', 0],
            ['boards_history_all', 0],
            ['boards_export', 0],
            ['website_history_90', 0],
            ['website_history_180', 0],
            ['website_history_all', 0],
            ['website_export', 0],
            ['pins_history', 0],
            ['pins_export', 0],
            ['pins_date_custom', 0],
            ['pins_last_50', 1],
            ['pins_all_pins', 0],
            ['pins_history_90', 0],
            ['pins_history_180', 0],
            ['pins_history_all', 0],
            ['category_most_active', 1],
            ['category_most_viral', 1],
            ['category_history_90', 0],
            ['category_history_180', 0],
            ['category_history_all', 0],
            ['category_export', 0],
            ['daytime_chart_organic', 0],
            ['daytime_export', 0],
            ['trending_latest_50', 1],
            ['trending_latest_100', 0],
            ['trending_latest_500', 0],
            ['trending_latest_1000', 0],
            ['trending_export', 0],
            ['fans_export', 0],
            ['fans_num_results', 0],
            ['top_followers_export', 0],
            ['top_followers_100', 0],
            ['top_followers_num_results', 0],
            ['top_pinners_100', 0],
            ['top_pinners_7_days', 0],
            ['top_pinners_14_days', 0],
            ['top_pinners_30_days', 0],
            ['top_pinners_export', 0],
            ['top_pinners_following', 0],
            ['top_pinners_num_results', 0],
            ['top_pinners_history_90', 0],
            ['top_pinners_history_180', 0],
            ['top_pinners_history_all', 0],
            ['top_engagers_100', 0],
            ['top_engagers_7_days', 0],
            ['top_engagers_14_days', 0],
            ['top_engagers_30_days', 0],
            ['top_engagers_export', 0],
            ['top_engagers_num_results', 0],
            ['top_engagers_history_90', 0],
            ['top_engagers_history_180', 0],
            ['top_engagers_history_all', 0],
            ['traffic_history_90', 0],
            ['traffic_history_180', 0],
            ['traffic_history_all', 0],
            ['traffic_export', 0],
            ['traffic_date_7_days', 1],
            ['traffic_date_14_days', 0],
            ['traffic_date_30_days', 0],
            ['traffic_date_custom', 0],
            ['comp_bench_history_90', 1],
            ['comp_bench_history_180', 0],
            ['comp_bench_history_all', 0],
            ['comp_bench_export', 0],
            ['comp_intel_history_90', 0],
            ['comp_intel_history_180', 0],
            ['comp_intel_history_all', 0],
            ['comp_intel_export', 0],
            ['settings_upgrade_button', 1],
            ['comp_add_any', 0],
            ['comp_add_2', 0],
            ['comp_add_5', 0],
            ['num_competitors', 0],
            ['num_accounts', 1],
            ['num_users', 3],
            ['comp_bench_domains', 0],
            ['fans_10_users', 0],
            ['nav_repinners', 0],
            ['nav_domain_pinners', 0],
            ['nav_newest_followers', 1],
            ['newest_followers_10', 1],
            ['category_footprint', 0],
            ['pins_last_250', 1],
            ['nav_viral_pins', 0],
            ['viral_pin_context', 0],
            ['viral_pin_history_90', 0],
            ['viral_pin_history_180', 0],
            ['viral_pin_export', 0],
            ['listening_data_age_max', 7],
            ['listening_insights_dailyvolume_menu', 0],
            ['listening_popularfeeds', 0],
            ['listening_insights_topsources', 0],
            ['listening_insights_toppinners', 5],
            ['listening_query_topics_max', 1],
            ['nav_comp_intel',0],
            ['profile_date_chart_repins',0],
            ['profile_date_chart_likes',0],
            ['profile_date_gauges',0],
            ['tasks_list_enabled',1],
            ['side_nav_version',3],
            ['dashboard_enabled', 1],
            ['peak_days_and_times_enabled',0],
            ['domain_data_age_max',7],
            ['domain_custom_date_range',0],
            ['domain_trending_images',0],
            ['domain_history_alltime',0],
            ['domain_insights_custom_date_range',0],
            ['domain_data_update_frequency',60],
            ['google_analytics_update_frequency',1440],
            ['domain_popularfeeds',0],
            ['domain_insights_dailyvolume_menu', 0],
            ['domain_insights_topsources',0],
            ['domain_insights_toppinners',0],
            ['domain_query_topic_max',1],
            ['domain_feeds_extra_date_ranges',0],
            ['domain_impressions_history',0],
            ['domain_insights_hashtags',0],
            ['domain_hashtags_feed',0],
            ['content_flagging', 0],
            ['pinterest_oauth_enabled',0]
        );

        $lite_plan = array(
            'nav_profile' => 1,
            'nav_boards' => 1,
            'nav_website' => 1,
            'nav_pins' => 1,
            'nav_category' => 0,
            'nav_day_time' => 1,
            'nav_trending_pins' => 1,
            'nav_fans' => 1,
            'nav_traffic' => 1,
            'nav_roi_pins' => 0,
            'nav_roi_pinners' => 0,
            'nav_comp_bench' => 0,
            'nav_listen' => 0,
            'nav_add_account' => 1,
            'nav_add_user' => 1,
            'profile_date_7_days' => 1,
            'profile_date_14_days' => 1,
            'profile_date_30_days' => 1,
            'profile_date_custom' => 1,
            'profile_history_90' => 1,
            'profile_history_180' => 0,
            'profile_history_all' => 0,
            'profile_chart_repins' => 1,
            'profile_chart_likes' => 1,
            'profile_gauges' => 1,
            'profile_export' => 0,
            'boards_date_7_days' => 1,
            'boards_date_14_days' => 1,
            'boards_date_30_days' => 1,
            'boards_date_custom' => 1,
            'boards_history_90' => 1,
            'boards_history_180' => 0,
            'boards_history_all' => 0,
            'boards_export' => 0,
            'website_history_90' => 1,
            'website_history_180' => 0,
            'website_history_all' => 0,
            'website_export' => 0,
            'pins_history' => 0,
            'pins_export' => 0,
            'pins_date_custom' => 1,
            'pins_last_50' => 1,
            'pins_all_pins' => 1,
            'pins_history_90' => 1,
            'pins_history_180' => 0,
            'pins_history_all' => 0,
            'category_most_active' => 1,
            'category_most_viral' => 1,
            'category_history_90' => 1,
            'category_history_180' => 0,
            'category_history_all' => 0,
            'category_export' => 0,
            'daytime_chart_organic' => 0,
            'daytime_export' => 0,
            'trending_latest_50' => 1,
            'trending_latest_100' => 1,
            'trending_latest_500' => 1,
            'trending_latest_1000' => 0,
            'trending_export' => 0,
            'fans_export' => 0,
            'fans_num_results' => 0,
            'top_followers_export' => 0,
            'top_followers_100' => 1,
            'top_followers_num_results' => 0,
            'top_pinners_100' => 1,
            'top_pinners_7_days' => 0,
            'top_pinners_14_days' => 0,
            'top_pinners_30_days' => 0,
            'top_pinners_export' => 0,
            'top_pinners_following' => 1,
            'top_pinners_num_results' => 0,
            'top_pinners_history_90' => 0,
            'top_pinners_history_180' => 0,
            'top_pinners_history_all' => 0,
            'top_engagers_100' => 1,
            'top_engagers_7_days' => 0,
            'top_engagers_14_days' => 0,
            'top_engagers_30_days' => 0,
            'top_engagers_export' => 0,
            'top_engagers_num_results' => 0,
            'top_engagers_history_90' => 0,
            'top_engagers_history_180' => 0,
            'top_engagers_history_all' => 0,
            'traffic_history_90' => 1,
            'traffic_history_180' => 0,
            'traffic_history_all' => 0,
            'traffic_export' => 0,
            'traffic_date_7_days' => 1,
            'traffic_date_14_days' => 1,
            'traffic_date_30_days' => 1,
            'traffic_date_custom' => 1,
            'comp_bench_history_90' => 0,
            'comp_bench_history_180' => 0,
            'comp_bench_history_all' => 0,
            'comp_bench_export' => 0,
            'comp_intel_history_90' => 0,
            'comp_intel_history_180' => 0,
            'comp_intel_history_all' => 0,
            'comp_intel_export' => 0,
            'settings_upgrade_button' => 1,
            'comp_add_any' => 0,
            'comp_add_2' => 0,
            'comp_add_5' => 0,
            'num_competitors' => 2,
            'num_accounts' => 1,
            'num_users' => 3,
            'comp_bench_domains' => 0,
            'fans_10_users' => 1,
            'nav_repinners' => 1,
            'nav_domain_pinners' => 1,
            'nav_newest_followers' => 1,
            'newest_followers_10' => 1,
            'category_footprint' => 0,
            'pins_last_250' => 1,
            'nav_viral_pins' => 1,
            'viral_pin_context' => 0,
            'viral_pin_history_90' => 1,
            'viral_pin_history_180' => 0,
            'viral_pin_export' => 0,
            'listening_data_age_max' => 90,
            'listening_insights_dailyvolume_menu' => 1,
            'listening_popularfeeds' => 1,
            'listening_insights_topsources' => 1,
            'listening_insights_toppinners' => 5,
            'listening_query_topics_max' => 1,
            'nav_comp_intel'=>1,
            'profile_date_chart_repins'=>1,
            'profile_date_chart_likes'=>1,
            'profile_date_gauges'=>1
        );

        $legacy_lite_plan = array(
            'nav_profile' => 1,
            'nav_boards' => 1,
            'nav_website' => 1,
            'nav_pins' => 1,
            'nav_category' => 1,
            'nav_day_time' => 1,
            'nav_trending_pins' => 1,
            'nav_fans' => 1,
            'nav_traffic' => 1,
            'nav_roi_pins' => 0,
            'nav_roi_pinners' => 0,
            'nav_comp_bench' => 1,
            'nav_listen' => 0,
            'nav_add_account' => 1,
            'nav_add_user' => 1,
            'profile_date_7_days' => 1,
            'profile_date_14_days' => 1,
            'profile_date_30_days' => 1,
            'profile_date_custom' => 1,
            'profile_history_90' => 1,
            'profile_history_180' => 0,
            'profile_history_all' => 0,
            'profile_chart_repins' => 1,
            'profile_chart_likes' => 1,
            'profile_gauges' => 1,
            'profile_export' => 0,
            'boards_date_7_days' => 1,
            'boards_date_14_days' => 1,
            'boards_date_30_days' => 1,
            'boards_date_custom' => 1,
            'boards_history_90' => 1,
            'boards_history_180' => 0,
            'boards_history_all' => 0,
            'boards_export' => 0,
            'website_history_90' => 1,
            'website_history_180' => 0,
            'website_history_all' => 0,
            'website_export' => 0,
            'pins_history' => 0,
            'pins_export' => 0,
            'pins_date_custom' => 1,
            'pins_last_50' => 1,
            'pins_all_pins' => 1,
            'pins_history_90' => 1,
            'pins_history_180' => 0,
            'pins_history_all' => 0,
            'category_most_active' => 1,
            'category_most_viral' => 1,
            'category_history_90' => 1,
            'category_history_180' => 0,
            'category_history_all' => 0,
            'category_export' => 0,
            'daytime_chart_organic' => 0,
            'daytime_export' => 0,
            'trending_latest_50' => 1,
            'trending_latest_100' => 1,
            'trending_latest_500' => 1,
            'trending_latest_1000' => 0,
            'trending_export' => 0,
            'fans_export' => 0,
            'fans_num_results' => 0,
            'top_followers_export' => 0,
            'top_followers_100' => 1,
            'top_followers_num_results' => 0,
            'top_pinners_100' => 1,
            'top_pinners_7_days' => 0,
            'top_pinners_14_days' => 0,
            'top_pinners_30_days' => 0,
            'top_pinners_export' => 0,
            'top_pinners_following' => 1,
            'top_pinners_num_results' => 0,
            'top_pinners_history_90' => 0,
            'top_pinners_history_180' => 0,
            'top_pinners_history_all' => 0,
            'top_engagers_100' => 1,
            'top_engagers_7_days' => 0,
            'top_engagers_14_days' => 0,
            'top_engagers_30_days' => 0,
            'top_engagers_export' => 0,
            'top_engagers_num_results' => 0,
            'top_engagers_history_90' => 0,
            'top_engagers_history_180' => 0,
            'top_engagers_history_all' => 0,
            'traffic_history_90' => 1,
            'traffic_history_180' => 0,
            'traffic_history_all' => 0,
            'traffic_export' => 0,
            'traffic_date_7_days' => 1,
            'traffic_date_14_days' => 1,
            'traffic_date_30_days' => 1,
            'traffic_date_custom' => 1,
            'comp_bench_history_90' => 1,
            'comp_bench_history_180' => 0,
            'comp_bench_history_all' => 0,
            'comp_bench_export' => 0,
            'comp_intel_history_90' => 0,
            'comp_intel_history_180' => 0,
            'comp_intel_history_all' => 0,
            'comp_intel_export' => 0,
            'settings_upgrade_button' => 1,
            'comp_add_any' => 0,
            'comp_add_2' => 1,
            'comp_add_5' => 0,
            'num_competitors' => 2,
            'num_accounts' => 1,
            'num_users' => 3,
            'comp_bench_domains' => 0,
            'fans_10_users' => 1,
            'nav_repinners' => 1,
            'nav_domain_pinners' => 1,
            'nav_newest_followers' => 1,
            'newest_followers_10' => 1,
            'category_footprint' => 0,
            'pins_last_250' => 1,
            'nav_viral_pins' => 1,
            'viral_pin_context' => 0,
            'viral_pin_history_90' => 1,
            'viral_pin_history_180' => 0,
            'viral_pin_export' => 0,
            'listening_data_age_max' => 90,
            'listening_insights_dailyvolume_menu' => 1,
            'listening_popularfeeds' => 1,
            'listening_insights_topsources' => 1,
            'listening_insights_toppinners' => 5,
            'listening_query_topics_max' => 1,
            'nav_comp_intel'=>1,
            'profile_date_chart_repins'=>1,
            'profile_date_chart_likes'=>1,
            'profile_date_gauges'=>1
        );

        $pro_plan = array(
            'nav_profile' => 1,
            'nav_boards' => 1,
            'nav_website' => 1,
            'nav_pins' => 1,
            'nav_category' => 1,
            'nav_day_time' => 1,
            'nav_trending_pins' => 1,
            'nav_fans' => 1,
            'nav_traffic' => 1,
            'nav_roi_pins' => 1,
            'nav_roi_pinners' => 1,
            'nav_comp_bench' => 1,
            'nav_listen' => 0,
            'nav_add_account' => 1,
            'nav_add_user' => 1,
            'profile_date_7_days' => 1,
            'profile_date_14_days' => 1,
            'profile_date_30_days' => 1,
            'profile_date_custom' => 1,
            'profile_history_90' => 1,
            'profile_history_180' => 1,
            'profile_history_all' => 0,
            'profile_chart_repins' => 1,
            'profile_chart_likes' => 1,
            'profile_gauges' => 1,
            'profile_export' => 1,
            'boards_date_7_days' => 1,
            'boards_date_14_days' => 1,
            'boards_date_30_days' => 1,
            'boards_date_custom' => 1,
            'boards_history_90' => 1,
            'boards_history_180' => 1,
            'boards_history_all' => 0,
            'boards_export' => 1,
            'website_history_90' => 1,
            'website_history_180' => 1,
            'website_history_all' => 0,
            'website_export' => 1,
            'pins_history' => 1,
            'pins_export' => 1,
            'pins_date_custom' => 1,
            'pins_last_50' => 1,
            'pins_all_pins' => 1,
            'pins_history_90' => 1,
            'pins_history_180' => 1,
            'pins_history_all' => 0,
            'category_most_active' => 1,
            'category_most_viral' => 1,
            'category_history_90' => 1,
            'category_history_180' => 1,
            'category_history_all' => 0,
            'category_export' => 1,
            'daytime_chart_organic' => 1,
            'daytime_export' => 1,
            'trending_latest_50' => 1,
            'trending_latest_100' => 1,
            'trending_latest_500' => 1,
            'trending_latest_1000' => 1,
            'trending_export' => 1,
            'fans_export' => 1,
            'fans_num_results' => 0,
            'top_followers_export' => 0,
            'top_followers_100' => 0,
            'top_followers_num_results' => 0,
            'top_pinners_100' => 1,
            'top_pinners_7_days' => 1,
            'top_pinners_14_days' => 1,
            'top_pinners_30_days' => 1,
            'top_pinners_export' => 1,
            'top_pinners_following' => 1,
            'top_pinners_num_results' => 0,
            'top_pinners_history_90' => 1,
            'top_pinners_history_180' => 1,
            'top_pinners_history_all' => 0,
            'top_engagers_100' => 1,
            'top_engagers_7_days' => 1,
            'top_engagers_14_days' => 1,
            'top_engagers_30_days' => 1,
            'top_engagers_export' => 1,
            'top_engagers_num_results' => 0,
            'top_engagers_history_90' => 1,
            'top_engagers_history_180' => 1,
            'top_engagers_history_all' => 0,
            'traffic_history_90' => 1,
            'traffic_history_180' => 1,
            'traffic_history_all' => 0,
            'traffic_export' => 1,
            'traffic_date_7_days' => 1,
            'traffic_date_14_days' => 1,
            'traffic_date_30_days' => 1,
            'traffic_date_custom' => 1,
            'comp_bench_history_90' => 1,
            'comp_bench_history_180' => 1,
            'comp_bench_history_all' => 0,
            'comp_bench_export' => 1,
            'comp_intel_history_90' => 1,
            'comp_intel_history_180' => 1,
            'comp_intel_history_all' => 0,
            'comp_intel_export' => 1,
            'settings_upgrade_button' => 1,
            'comp_add_any' => 0,
            'comp_add_2' => 1,
            'comp_add_5' => 1,
            'followers_export' => 1,
            'num_competitors' => 5,
            'num_accounts' => 1,
            'num_users' => 3,
            'comp_bench_domains' => 1,
            'fans_10_users' => 0,
            'nav_repinners' => 1,
            'nav_domain_pinners' => 1,
            'nav_newest_followers' => 1,
            'newest_followers_10' => 0,
            'category_footprint' => 1,
            'pins_last_250' => 1,
            'nav_viral_pins' => 1,
            'viral_pin_context' => 1,
            'viral_pin_history_90' => 1,
            'viral_pin_history_180' => 1,
            'viral_pin_export' => 1,
            'listening_data_age_max' => 365,
            'listening_insights_dailyvolume_menu' => 1,
            'listening_popularfeeds' => 1,
            'listening_insights_topsources' => 1,
            'listening_insights_toppinners' => 25,
            'listening_query_topics_max' => 25,
            'nav_comp_intel'=>1,
            'profile_date_chart_repins'=>1,
            'profile_date_chart_likes'=>1,
            'profile_date_gauges'=>1,
            'peak_days_and_times_enabled'=>1
        );

        $legacy_pro_plan = array(
            'nav_profile' => 1,
            'nav_boards' => 1,
            'nav_website' => 1,
            'nav_pins' => 1,
            'nav_category' => 1,
            'nav_day_time' => 1,
            'nav_trending_pins' => 1,
            'nav_fans' => 1,
            'nav_traffic' => 1,
            'nav_roi_pins' => 1,
            'nav_roi_pinners' => 1,
            'nav_comp_bench' => 1,
            'nav_listen' => 0,
            'nav_add_account' => 1,
            'nav_add_user' => 1,
            'profile_date_7_days' => 1,
            'profile_date_14_days' => 1,
            'profile_date_30_days' => 1,
            'profile_date_custom' => 1,
            'profile_history_90' => 1,
            'profile_history_180' => 1,
            'profile_history_all' => 0,
            'profile_chart_repins' => 1,
            'profile_chart_likes' => 1,
            'profile_gauges' => 1,
            'profile_export' => 1,
            'boards_date_7_days' => 1,
            'boards_date_14_days' => 1,
            'boards_date_30_days' => 1,
            'boards_date_custom' => 1,
            'boards_history_90' => 1,
            'boards_history_180' => 1,
            'boards_history_all' => 0,
            'boards_export' => 1,
            'website_history_90' => 1,
            'website_history_180' => 1,
            'website_history_all' => 0,
            'website_export' => 1,
            'pins_history' => 1,
            'pins_export' => 1,
            'pins_date_custom' => 1,
            'pins_last_50' => 1,
            'pins_all_pins' => 1,
            'pins_history_90' => 1,
            'pins_history_180' => 1,
            'pins_history_all' => 0,
            'category_most_active' => 1,
            'category_most_viral' => 1,
            'category_history_90' => 1,
            'category_history_180' => 1,
            'category_history_all' => 0,
            'category_export' => 1,
            'daytime_chart_organic' => 1,
            'daytime_export' => 1,
            'trending_latest_50' => 1,
            'trending_latest_100' => 1,
            'trending_latest_500' => 1,
            'trending_latest_1000' => 1,
            'trending_export' => 1,
            'fans_export' => 1,
            'fans_num_results' => 0,
            'top_followers_export' => 0,
            'top_followers_100' => 0,
            'top_followers_num_results' => 0,
            'top_pinners_100' => 1,
            'top_pinners_7_days' => 1,
            'top_pinners_14_days' => 1,
            'top_pinners_30_days' => 1,
            'top_pinners_export' => 1,
            'top_pinners_following' => 1,
            'top_pinners_num_results' => 0,
            'top_pinners_history_90' => 1,
            'top_pinners_history_180' => 1,
            'top_pinners_history_all' => 0,
            'top_engagers_100' => 1,
            'top_engagers_7_days' => 1,
            'top_engagers_14_days' => 1,
            'top_engagers_30_days' => 1,
            'top_engagers_export' => 1,
            'top_engagers_num_results' => 0,
            'top_engagers_history_90' => 1,
            'top_engagers_history_180' => 1,
            'top_engagers_history_all' => 0,
            'traffic_history_90' => 1,
            'traffic_history_180' => 1,
            'traffic_history_all' => 0,
            'traffic_export' => 1,
            'traffic_date_7_days' => 1,
            'traffic_date_14_days' => 1,
            'traffic_date_30_days' => 1,
            'traffic_date_custom' => 1,
            'comp_bench_history_90' => 1,
            'comp_bench_history_180' => 1,
            'comp_bench_history_all' => 0,
            'comp_bench_export' => 1,
            'comp_intel_history_90' => 1,
            'comp_intel_history_180' => 1,
            'comp_intel_history_all' => 0,
            'comp_intel_export' => 1,
            'settings_upgrade_button' => 1,
            'comp_add_any' => 0,
            'comp_add_2' => 1,
            'comp_add_5' => 1,
            'followers_export' => 1,
            'num_competitors' => 5,
            'num_accounts' => 1,
            'num_users' => 3,
            'comp_bench_domains' => 1,
            'fans_10_users' => 0,
            'nav_repinners' => 1,
            'nav_domain_pinners' => 1,
            'nav_newest_followers' => 1,
            'newest_followers_10' => 0,
            'category_footprint' => 1,
            'pins_last_250' => 1,
            'nav_viral_pins' => 1,
            'viral_pin_context' => 1,
            'viral_pin_history_90' => 1,
            'viral_pin_history_180' => 1,
            'viral_pin_export' => 1,
            'listening_data_age_max' => 365,
            'listening_insights_dailyvolume_menu' => 1,
            'listening_popularfeeds' => 1,
            'listening_insights_topsources' => 1,
            'listening_insights_toppinners' => 25,
            'listening_query_topics_max' => 25,
            'nav_comp_intel'=>1,
            'profile_date_chart_repins'=>1,
            'profile_date_chart_likes'=>1,
            'profile_date_gauges'=>1
        );

        DB::table('features')->truncate();
        DB::table('plan_features')->truncate();

        foreach ($defaults as list($name, $default)) {

            DB::insert('INSERT INTO features (`name`,`value`,`added_at`,`updated_at`) VALUES (?,?,?,?)',
                       [$name, $default, time(), time()]);

        }

        foreach ($lite_plan as $name=> $default) {

            $feature = DB::select('select feature_id from features where `name` = ?',[$name]);
            DB::insert('INSERT INTO plan_features (`plan_id`,`feature_id`,`value`,`added_at`,`updated_at`) VALUES (?,?,?,?,?)',
                       [2,$feature[0]->feature_id, $default, time(), time()]);

        }

        foreach ($pro_plan as $name=> $default) {

            $feature = DB::select('select feature_id from features where `name` = ?',[$name]);
            if ($feature) {
                DB::insert('INSERT INTO plan_features (`plan_id`,`feature_id`,`value`,`added_at`,`updated_at`) VALUES (?,?,?,?,?)',
                           [3,$feature[0]->feature_id, $default, time(), time()]);
            }

        }

        foreach ($pro_plan as $name=> $default) {

            $feature = DB::select('select feature_id from features where `name` = ?',[$name]);
            if ($feature) {
                DB::insert('INSERT INTO plan_features (`plan_id`,`feature_id`,`value`,`added_at`,`updated_at`) VALUES (?,?,?,?,?)',
                           [4,$feature[0]->feature_id, $default, time(), time()]);
            }
        }
        foreach ($legacy_lite_plan as $name=> $default) {

            $feature = DB::select('select feature_id from features where `name` = ?',[$name]);
            if ($feature) {
                DB::insert('INSERT INTO plan_features (`plan_id`,`feature_id`,`value`,`added_at`,`updated_at`) VALUES (?,?,?,?,?)',
                           [5,$feature[0]->feature_id, $default, time(), time()]);
            }
        }

        foreach ($legacy_pro_plan as $name=> $default) {

            $feature = DB::select('select feature_id from features where `name` = ?',[$name]);
            if ($feature) {
                DB::insert('INSERT INTO plan_features (`plan_id`,`feature_id`,`value`,`added_at`,`updated_at`) VALUES (?,?,?,?,?)',
                           [6,$feature[0]->feature_id, $default, time(), time()]);
            }
        }


    }

}
