<?php
return array(
    'beaver_facts' => array(
        'An adult beaver is approximately 3 feet long.',
        'Adult beavers have long flat tails that are about a foot long.',
        'Beavers slap their tails on the water surface as an alarm to alert the colony when they sense danger.',
        'An adult beaver can weigh between 30 and 70 pounds.',
        'Female beavers are larger than male beavers of the same age',
        'Beavers are nocturnal creatures and they work at night.',
        'Beavers are monogamous',
        'Beavers have poor sight but a strong sense of smell and good hearing.',
        'Beavers move slow on land but are good swimmers and can swim up to 5 mph.',
        'Beavers can stay underwater for up to 15 minutes.',
        'Prior to European immigration there were over 60 million beavers in North America.',
        'Due primarily to over trapping beavers were an endangered species in the early part of the 20th Century.',
        'Beavers have sharp teeth which continue to grow throughout their lifetimes.',
        'Beavers are found by streams, ponds, rivers and lakes.',
        'Beavers cut trees with their sharp teeth, build dams and create ponds and wetlands.',
        'Beavers are herbivores.',
        'Beavers feed on trees and tree bark; common favorites are cherry, maple, birch and aspens. Beavers also feed on water lilies, pondweed and leaves.',
        'Beavers live in colonies made up of a family of an adult male and female and 2-4 kits.',
        'A newborn beaver through the first year is called a kit while a young beaver in the second year of life is called a yearling.',
        'Beavers are very active on Pinterest and often are considered social media mavens.',
        'Beavers are territorial; they mark and protect their space.',
        'Beavers build dams and lodges. Dams and lodges are built for protection against predators such as wolves, coyotes, bears and eagles.',
        'Lodges are the homes of beavers and the beavers make them from sticks and mud.',
        'The entrance to lodge is underwater further protecting the beaver colony.',
        'Beavers do not hibernate and lodges need to be built in deep enough water so the entrance does not freeze in the winter.',
        'The English verb "to beaver" means to work hard and constantly.',
        'The beaver is the official symbol of the Canadian Military Engineers.',
        'The beaver was chosen to be the mascot of the 1976 Summer Olympics held in Montreal',
        'Beaver Buzz is an energy drink line produced in Canada',
        'The Beaver is the mascot of the City College of New York',
        'January and February is the mating season for beavers and beavers start mating during their second winter.',
        'Will Washburn attended High School at Tabor Academy in Marion, Massachusetts, where the mascot is the SeaWolf.',
        'Will Washburn is a Capricorn, and enjoys playing Basketball.',
        'Will Washburn loves his navy blue blazer and has been known to tear up the dance floor.',
        'Before Tailwind, D-Spossy Spoz was a underground electro-funk DJ in Portland, ME.',
        'While Yesh prefers Yeshy-poo, he still responds to his given name of Keerthi.',
        'Created in 2013, Twapp.com was home to the world\'s first beaver social network',
        'Fluffy peanut butter pinecones in a waffle maker are a beavers greatest invention.',
        'You must work out because you LOOK SO GOOD TODAY.',
        'Despite the rumors, Alex did not invent edible underwear. He just perfected it.',
        'Alex really is the quintessential tech guy.',
        'Before Tailwind, Yesh started a professional wiffle ball team in Kansas.',
        'Alex once ordered in French at a Spanish restaurant. He did not get his fries.',
        'Tailwindo is the Spanish term for Tailwind',
        'Thanks for the feedback everyone! - Alex',
        'What did the beaver say when his home fell down? Dam it!',
        'Before Tailwind, Tornadio and TankGoBoom were in the running to replace Pinleague as the company brand.',
        'Will has deleted his own ssh config before. Twice.',
        'At a young age, Danny Maloney decided he wanted to be famous in Topeka. In 2013, he achieved his goal.',
        'Pinleague is a French term for items that increase in value over time',
        'Will went through a period of homelessness in 2012.',
        'You look so money today. Must be the hair.',
        'Two-Chainz once took lessons from Danny Maloney about Pinning strategies. A duet is rumored to be in the works.',
        'In 2009 Melissa Megginson was rumored to replace Halle Berrie in the ill-fated Catwoman sequel (GrumpyCat\'s revenge) . Poor box office performance of the original was cited as the reason for cancellation.',
        'Yesh is the wheat man. He will always trade for sheep.',
        'Of all the animals of the world, the beaver is noted for his engineering and mechanical skill and habits of industry. His habits are nocturnal, he does his best work in the dark.',
        'Will Smith has been quoted saying that the inspiration for his 1997 smash "Gettin\' Jiggy Wit It" was from watching Jessica break it down on the dance floor.',
        'Ivan is pretty bad at ping pong.'

    )
);